name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  packages: read
  security-events: write
  issues: write

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/go-hello
  HELM_REPO: your-username/helm-charts # แก้เป็น repo ของคุณ
  PROJECT_ID: test1-403420
  GKE_ZONE: asia-southeast1

jobs:
  test:
    name: Test Application
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.4'

    - name: Run Tests
      run: go test -v ./...

  build-and-push:
    name: Build & Push Docker Image
    needs: test
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.vars.outputs.SHORT_SHA }}
    steps:
    - uses: actions/checkout@v3
    
    - name: Set variables
      id: vars
      run: |
        echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
        echo "BUILD_TIME=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: 'arm64,amd64'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          ${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.SHORT_SHA }}
          ${{ env.IMAGE_NAME }}:latest
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new
        build-args: |
          BUILD_TIME=${{ steps.vars.outputs.BUILD_TIME }}
          GIT_SHA=${{ github.sha }}

  security-scan:
    name: Security Scanning
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.IMAGE_NAME }}:${{ needs.build-and-push.outputs.image_tag }}
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL,HIGH'

    - name: Upload Trivy scan results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'

  update-helm:
    name: Update Helm Chart
    needs: [build-and-push, security-scan]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Checkout Helm repository
      uses: actions/checkout@v4
      with:
        repository: ${{ env.HELM_REPO }}
        token: ${{ secrets.HELM_REPO_TOKEN }}
        ref: main
        path: helm-charts

    - name: Update Helm values
      run: |
        cd helm-charts
        # Update image tag
        yq e ".image.tag = \"${{ needs.build-and-push.outputs.image_tag }}\"" -i values.yaml
        yq e ".image.repository = \"${{ env.IMAGE_NAME }}\"" -i values.yaml
        
        # Update chart version
        CHART_VERSION=$(yq e '.version' Chart.yaml)
        NEW_VERSION=$(echo $CHART_VERSION | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
        yq e ".version = \"$NEW_VERSION\"" -i Chart.yaml

    - name: Configure Git
      run: |
        cd helm-charts
        git config --local user.name 'github-actions[bot]'
        git config --local user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Commit and push changes
      run: |
        cd helm-charts
        git add .
        git commit -m "chore: update image tag to ${{ needs.build-and-push.outputs.image_tag }} [skip ci]"
        git push origin main

  deploy:
    name: Deploy to GKE
    needs: [update-helm, build-and-push]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Helm repository
      uses: actions/checkout@v4
      with:
        repository: ${{ env.HELM_REPO }}
        token: ${{ secrets.HELM_REPO_TOKEN }}
        ref: main
        path: helm-charts

    - name: Setup GCloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ env.PROJECT_ID }}

    - name: Get GKE Credentials
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: ${{ secrets.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        credentials: ${{ secrets.GKE_SA_KEY }}

    - name: Install Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.12.0

    - name: Deploy with Helm
      run: |
        cd helm-charts
        helm upgrade --install go-hello . \
          --namespace test \
          --create-namespace \
          --wait \
          --timeout 5m \
          --set image.tag=${{ needs.build-and-push.outputs.image_tag }}

    - name: Verify deployment
      run: |
        kubectl rollout status deployment/go-hello -n test